### ISSUE TITLE
5.99 (nightly) schematic not recognized?

### ISSUE THREAD

**Issue by ckuhtz** [BPJWES/KiCAD_Partslist_editor#13]
I tried to import a .kicad_sch file and failed. Is there a way to make this work or is this unsupported?

**Comment by BPJWES** [comment]
In KiCad 5.99 (And thus the upcoming v6) the schematic file format has been completely changed. This would require writing a new parser. Which can be done, but I have not planned doing so myself yet, as I consider the edit table functionality within the schematic editor to have mostly replaced the functionality in the KiCAD partslist editor script. 
![afbeelding](https://user-images.githubusercontent.com/13208934/111662711-7775df80-8810-11eb-96ea-d22108017a63.png)


You might also take a look at KiField which has similar functionality, although I am not sure if that runs parses KiCad v5.99 schematic files yet.

**Comment by christiankuhtz** [comment]
Thank you. Looks like nobody has picked this format up yet. Please close.
